#!/bin/bash

echo "Font Revealer for Adobe Creative Cloud - Alex's Version"

echo "Dry-Run will preview the renaming process without copy any files."
select dce in "Dry-Run" "Copy" "Exit"; do
    case $dce in
        Dry-Run ) isDry=true; echo "Dry-running..."; break;;
        Copy ) isDry=false; echo "Copy & rename files..."; break;;
        Exit ) exit;;
    esac
done

cd /mnt/c/Users/cpadmin/AppData/Roaming/Adobe/CoreSync/plugins/livetype/r
out=/mnt/c/Users/cpadmin/Downloads/AdobeFonts

# grab all otf dot files (adjust to your needs)
for file in ./* #.otf
do  
  # the "Postscript name:" does not contain spaces. good for file names.
  fontName=`/mnt/c/_git/adobe-fonts-revealer/bin/otfinfo.exe --info ${file} | fgrep "PostScript name:" | grep -oE "[^ ]+$"`
  fontName=$(echo "$fontName" | tr -cd '[:alnum:]')
  if [ "$isDry" = false ] ; then
    # create a FONT dir within downloads, if there is none
    mkdir -p $out/
    # copy files (if no dry-run)
    cp $file "$out/$fontName.otf"
  fi

  echo $out/$fontName.otf
done

echo "DONE! Check your 'AdobeFonts' directory within Downloads if you selected Option 2 (Copy)"
